// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xP-1Gd--Wj2Z34pM57appbofTKkIarc',
    appId: '1:443243023254:web:c93f53cc0fe825d49cabb7',
    messagingSenderId: '443243023254',
    projectId: 'batch-13-f1d8c',
    authDomain: 'batch-13-f1d8c.firebaseapp.com',
    storageBucket: 'batch-13-f1d8c.firebasestorage.app',
    measurementId: 'G-68J8ME4W83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAziC9_wTXDAWX0RIUKWBgVqoDuByR1z_M',
    appId: '1:443243023254:android:dcbf6fb64cf1174e9cabb7',
    messagingSenderId: '443243023254',
    projectId: 'batch-13-f1d8c',
    storageBucket: 'batch-13-f1d8c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_xP-1Gd--Wj2Z34pM57appbofTKkIarc',
    appId: '1:443243023254:web:dc7cf8e46ce7a4899cabb7',
    messagingSenderId: '443243023254',
    projectId: 'batch-13-f1d8c',
    authDomain: 'batch-13-f1d8c.firebaseapp.com',
    storageBucket: 'batch-13-f1d8c.firebasestorage.app',
    measurementId: 'G-GSF74Q3E4R',
  );
}
