// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDre8eliIJHpeknLKNuXq_TCxyk84WQUTI',
    appId: '1:681468725026:web:5d34bbe325abbb5e71c77b',
    messagingSenderId: '681468725026',
    projectId: 'students-13-39e9f',
    authDomain: 'students-13-39e9f.firebaseapp.com',
    storageBucket: 'students-13-39e9f.firebasestorage.app',
    measurementId: 'G-QLLFZNF6VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdkez0iKWVhOm0rTJJZTS2pb7ezTE8bw',
    appId: '1:681468725026:android:5091aee842320cb871c77b',
    messagingSenderId: '681468725026',
    projectId: 'students-13-39e9f',
    storageBucket: 'students-13-39e9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq_560gtl-sHz-uROB3qO_ADSGA3K4l_0',
    appId: '1:681468725026:ios:3514752c11b42e3771c77b',
    messagingSenderId: '681468725026',
    projectId: 'students-13-39e9f',
    storageBucket: 'students-13-39e9f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq_560gtl-sHz-uROB3qO_ADSGA3K4l_0',
    appId: '1:681468725026:ios:3514752c11b42e3771c77b',
    messagingSenderId: '681468725026',
    projectId: 'students-13-39e9f',
    storageBucket: 'students-13-39e9f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDre8eliIJHpeknLKNuXq_TCxyk84WQUTI',
    appId: '1:681468725026:web:e1eb07a5a98005a171c77b',
    messagingSenderId: '681468725026',
    projectId: 'students-13-39e9f',
    authDomain: 'students-13-39e9f.firebaseapp.com',
    storageBucket: 'students-13-39e9f.firebasestorage.app',
    measurementId: 'G-NC8LXSTK0W',
  );

}